#!/bin/sh

# _site폴더가 생성되었다고 가정하고 실행

cd ./_site

echo "--------- check status"
git status
git remote -v

echo "--------- add"
git add -A

echo "--------- commit"
now=$(date +'%Y-%m-%d %T')
message="Update message $now"
git commit -m "$message"

echo "--------- push"
git push deploy master
